// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fct_c_optimize
List fct_c_optimize(arma::sp_mat x, arma::mat u, arma::mat v, arma::sp_mat w, arma::mat index, double lambda, double epsilon, int maxiter);
RcppExport SEXP _smoothLRC_fct_c_optimize(SEXP xSEXP, SEXP uSEXP, SEXP vSEXP, SEXP wSEXP, SEXP indexSEXP, SEXP lambdaSEXP, SEXP epsilonSEXP, SEXP maxiterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type u(uSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type v(vSEXP);
    Rcpp::traits::input_parameter< arma::sp_mat >::type w(wSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type index(indexSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    rcpp_result_gen = Rcpp::wrap(fct_c_optimize(x, u, v, w, index, lambda, epsilon, maxiter));
    return rcpp_result_gen;
END_RCPP
}
// obs_log_like
arma::rowvec obs_log_like(arma::sp_mat test_x, arma::mat u, arma::mat v, arma::mat test_nn, arma::mat index_map);
RcppExport SEXP _smoothLRC_obs_log_like(SEXP test_xSEXP, SEXP uSEXP, SEXP vSEXP, SEXP test_nnSEXP, SEXP index_mapSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat >::type test_x(test_xSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type u(uSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type v(vSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type test_nn(test_nnSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type index_map(index_mapSEXP);
    rcpp_result_gen = Rcpp::wrap(obs_log_like(test_x, u, v, test_nn, index_map));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_smoothLRC_fct_c_optimize", (DL_FUNC) &_smoothLRC_fct_c_optimize, 8},
    {"_smoothLRC_obs_log_like", (DL_FUNC) &_smoothLRC_obs_log_like, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_smoothLRC(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
